[workspace]
resolver = "2"
members = ["crates/*"]
default-members = [
    "crates/symbolicator",
    "crates/symbolicli",
    "crates/symsorter",
    "crates/wasm-split",
]

[profile.dev]
# For debug builds, we do want to optimize for both debug-ability, and fast iteration times.
# To de able to "Debug Test", we do need full debug info.
# However especially on MacOS, incremental build times are primarily dominated by linking time.
# To help with that, one can try using `lld` as linker by adding the following to `.cargo/config.toml`:
# [build]
# rustflags = ["-C", "linker-flavor=ld64.lld"]
# OR (which I believe is equivalent):
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.release]
# For release builds, we do want line-only debug information to be able to symbolicate panic stack traces.
debug = 1

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true

[profile.local]
# For running a local symbolicator, we want the best of both worlds: a fast executable, with quick
# iteration times.
# You can compile/run this with: `cargo run --profile local -- --config local.yml run`
inherits = "release"
debug = false
incremental = true
codegen-units = 256

[patch.crates-io]
# This patch adds an `ip_filter` able to filter out internal IP addresses in DNS resolution
reqwest = { git = "https://github.com/getsentry/reqwest", branch = "restricted-connector" }

# This patch adds limited "templated lambdas" demangling support
cpp_demangle = { git = "https://github.com/getsentry/cpp_demangle", branch = "sentry-patches" }

# For local development: uncomment the following three lines (and adjust the path if necessary)
# to use a local symbolic checkout everywhere.
# This only works for the very specific crate listed here, and not for its dependency tree.
# Alternatively, the whole dependency tree can be changed at once by putting this line into
# `crates/symbolicator/Cargo.toml`:
# symbolic = { path = "../../../symbolic/symbolic", features = ["common-serde", "debuginfo", "demangle", "minidump-serde", "symcache"] }
# See also https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html
# [patch.crates-io]
# symbolic-debuginfo = { path = "../symbolic/symbolic-debuginfo" }

[workspace.dependencies]
reqwest = "0.12.2"
tokio = "1.36.0"
tokio-metrics = "0.3.1"
tokio-util = "0.7.10"
anyhow = "1.0.68"
apple-crash-report-parser = "0.5.1"
async-trait = "0.1.53"
aws-config = "1.0.1"
aws-credential-types = "1.0.1"
aws-sdk-s3 = "1.4.0"
aws-types = "1.0.1"
axum = "0.7.2"
axum-server = "0.6.0"
bindgen = "0.69.1"
cadence = "1.0.0"
chrono = { version = "0.4.19", default-features = false }
clap = "4.3.2"
cmake = "0.1.46"
console = "0.15.0"
crossbeam-utils = "0.8.19"
data-url = "0.3.0"
dirs = "5.0.0"
filetime = "0.2.16"
flate2 = "1.0.23"
futures = "0.3.12"
gcp_auth = "0.11.0"
glob = "0.3.0"
hex = "0.4.2"
hostname = "0.4.0"
humantime = "2.1.0"
humantime-serde = "1.1.1"
idna = "0.5.0"
insta = "1.18.0"
ipnetwork = "0.20.0"
jsonwebtoken = "9.1.0"
minidump = "0.21.0"
minidump-processor = "0.21.0"
minidump-unwind = "0.21.0"
moka = "0.12.1"
once_cell = "1.18.0"
prettytable-rs = "0.10.0"
proguard = "5.4.1"
rand = "0.8.5"
rayon = "1.5.2"
regex = "1.5.5"
rustc-hash = "1.1.0"
sentry = "0.32.1"
serde = "1.0.137"
serde_json = "1.0.94"
serde_yaml = "0.9.14"
sha-1 = "0.10.0"
sha2 = "0.10.6"
sketches-ddsketch = "0.2.2"
symbolic = "12.8.0"
symbolic-common = "12.7.1"
symbolicator-crash = { path = "crates/symbolicator-crash" }
symbolicator-js = { path = "crates/symbolicator-js" }
symbolicator-native = { path = "crates/symbolicator-native" }
symbolicator-proguard = { path = "crates/symbolicator-proguard" }
symbolicator-service = { path = "crates/symbolicator-service" }
symbolicator-sources = { path = "crates/symbolicator-sources" }
symbolicator-test = { path = "crates/symbolicator-test" }
tempfile = "3.10.0"
test-assembler = "0.1.5"
thiserror = "1.0.31"
thread_local = "1.1.7"
toml = "0.8.0"
tower = "0.4"
tower-http = "0.5.0"
tower-layer = "0.3"
tower-service = "0.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = "2.2.0"
uuid = "1.0.0"
walkdir = "2.3.1"
wasmbin = "0.8.1"
zip = { version = "0.6.4", default-features = false }
zstd = "0.13.0"
