[package]
name = "symbolicli"
version = "0.7.0"
edition = "2021"
authors = ["Sentry <hello@getsentry.com>"]
license = "MIT"

[dependencies]
anyhow = "1.0.66"
axum = "0.6.6"
clap = { version = "4.0.25", features = ["derive"] }
dirs = "4.0.0"
http-body-util = "0.1.0-rc.2"
hyper = { version = "0.14.24", features = ["full"] }
keyring = "2.0.1"
oauth2 = "4.3.0"
prettytable-rs = "0.10.0"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.137", features = ["derive", "rc"] }
serde_json = "1.0.81"
serde_yaml = "0.9.14"
symbolic = "11.0.0"
symbolicator-service = { path = "../symbolicator-service" }
symbolicator-sources = { path = "../symbolicator-sources" }
tempfile = "3.3.0"
tokio = { version = "1.24.2", features = ["rt-multi-thread", "macros", "time", "sync"] }
toml = "0.7.1"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["tracing-log", "local-time", "env-filter", "json"] }
url = "2.3.1"
