[package]
name = "process-event"
publish = false
version = "24.5.0"
authors = ["Sentry <hello@getsentry.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, features = ["blocking", "json", "multipart", "hickory-dns"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
symbolic-common = { workspace = true }
