[package]
name = "symsorter"
version = "24.5.0"
authors = ["Sentry <hello@getsentry.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["clock", "serde", "std"] }
clap = { workspace = true, features = ["derive"] }
console = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
symbolic = { workspace = true, features = ["debuginfo-serde"] }
walkdir = { workspace = true }
# NOTE: zip:0.6 by default depends on a version of zstd which conflicts with our other dependencies
zip = { workspace = true, features = ["deflate", "bzip2"] }
zstd = { workspace = true }
