[package]
name = "symbolicator-js"
publish = false
version = "24.5.0"
authors = ["Sentry <hello@getsentry.com>"]
edition = "2021"
license = "MIT"

[dependencies]
data-url = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
moka = { workspace = true, features = ["future", "sync"] }
once_cell = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["gzip", "brotli", "deflate", "json", "stream", "hickory-dns"] }
sentry = { workspace = true, features = ["tracing"] }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
symbolic = { workspace = true, features = ["common-serde", "sourcemapcache"] }
symbolicator-service = { workspace = true }
symbolicator-sources = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "fs"] }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
insta = { workspace = true, features = ["redactions", "yaml"] }
symbolicator-test = { workspace = true }
