[package]
name = "symbolicator-native"
publish = false
version = "24.5.0"
authors = ["Sentry <hello@getsentry.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
apple-crash-report-parser = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
futures = { workspace = true }
minidump = { workspace = true }
minidump-processor = { workspace = true }
minidump-unwind = { workspace = true }
moka = { workspace = true, features = ["future", "sync"] }
once_cell = { workspace = true }
regex = { workspace = true }
sentry = { workspace = true, features = ["tracing"] }
serde = { workspace = true, features = ["derive", "rc"] }
symbolic = { workspace = true, features = ["cfi", "common-serde", "debuginfo", "demangle", "symcache", "il2cpp", "ppdb"] }
symbolicator-service = { workspace = true }
symbolicator-sources = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
insta = { workspace = true, features = ["redactions", "yaml"] }
serde_json = { workspace = true }
symbolicator-test = { workspace = true }
test-assembler = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "fs"] }
